### ISSUE TITLE
Build fails when process is present  

### ISSUE THREAD

**Issue by NorbertBodziony** [divriots/vite-plugin-bundled-entry#2]
I got problem when i have defined  process in vite config
`  define: { 'process.env': {} }`
build throws:
```
[vite:plugin:bundled:entry:some_virtual_id] Build failed with 1 error:
error: Invalid define value (must be valid JSON syntax or a single identifier): [object Object]
```
Without define process works as expected

**Comment by gqio** [comment]
Hello,

I think for the define you need to pass a String.

for instance

`define : { 'process.env': JSON.stringify({}) }`

or 

`define : { 'process.env': '{}' }`

**Comment by NorbertBodziony** [comment]
Yeah that helps thanks !
